# Generated by Django 3.2.5 on 2021-07-22 23:34

import contact.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=15)),
                ('m_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(choices=[('home', 'home'), ('work', 'work'), ('cell', 'cell')], default='cell', max_length=5)),
                ('area_code', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=12, validators=[contact.models.Phone.val_number])),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('home', 'home'), ('work', 'work')], default='home', max_length=5)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=6)),
                ('zip', models.IntegerField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
            ],
        ),
    ]
