# Generated by Django 3.2.5 on 2021-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='l_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='m_name',
            new_name='mname',
        ),
        migrations.AddField(
            model_name='date',
            name='date_type',
            field=models.CharField(default='birth', max_length=10),
        ),
    ]
