# Generated by Django 3.2.5 on 2021-07-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210723_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_id',
            field=models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='date',
            name='contact_id',
            field=models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact_id',
            field=models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='contact.contact'),
        ),
    ]
