# Generated by Django 3.2.5 on 2021-07-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20210725_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
