# Generated by Django 3.2.5 on 2021-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_alter_contact_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work')], default='home', max_length=5),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work'), ('cell', 'cell')], default='cell', max_length=5),
        ),
    ]
