# Generated by Django 3.2.5 on 2021-07-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20210725_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_type',
            field=models.CharField(default='birth', max_length=10),
        ),
    ]
