# Generated by Django 3.2.5 on 2021-07-27 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_alter_date_date_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(regex='\\d{3}-{0,1}\\d{3}-{0,1}\\d{4}')]),
        ),
    ]
